SF-8245 | remove map_by and unmapped_policy from PersonalDriveMapping…
portalarchitects/skysync-cli pull request #167
Opened 2021-02-26 14:30 UTC by bentatum

…Convention interface + delete personalDriveExceptions.ts

2021-02-26 17:15 UTC, JimPartinSkySync commented
I think this should be removed (in src/sdk/resources/index.ts): https://github.com/portalarchitects/skysync-cli/blob/1b4538c9be08e7fc36646e58921298ae3f46999d/src/sdk/resources/index.ts#L26

2021-02-26 17:24 UTC, JimPartinSkySync requested changes
I think this should be removed (in src/sdk/resources/index.ts):

https://github.com/portalarchitects/skysync-cli/blob/1b4538c9be08e7fc36646e58921298ae3f46999d/src/sdk/resources/index.ts#L26

2021-03-01 14:21 UTC, JimPartinSkySync approved these changes

2021-03-01 14:42 UTC, avolinsky approved these changes

2021-03-01 14:56 UTC, merged