ACT-1091: Add entity type dictionary/elements support
portalarchitects/skysync-cli pull request #182
Opened 2021-06-02 18:34 UTC by JimPartinSkySync

Adding support for entity type dictionaries and entity type dictionary terms.

2021-06-04 12:59 UTC, gotvino approved these changes

2021-06-04 13:49 UTC, smbecker requested changes
Minor change for when we add dictionaries.

2021-06-04 13:49 UTC, smbecker commented on src/sdk/models/entityTypes.ts
> +	readonly?: boolean;
`elements?: EntityTypeDictionaryElement[]`

2021-06-04 16:29 UTC, avolinsky commented on src/sdk/models/entityTypes.ts
> +	keywords?: EntityTypeDictionary;
Same question as https://github.com/portalarchitects/skysync-cli/pull/181 Are we not going to create multiple EntityType classes like on back end? `keywords` property does not apply to `TransformEntityType`

cc: @bentatum, @gotvino, @smbecker

2021-06-08 00:11 UTC, jpartin2 commented
@gotvino @smbecker @avolinsky @bentatum  Added the distinct types for block list and pattern entity types. I added in Ben's regex patterns PR changes to this one just to build out the concept.

Please have a look and let me know any thoughts.

2021-06-08 00:12 UTC, jpartin2 commented on src/sdk/models/entityTypes.ts
> +	kind: 'block_list';
Did we want the discriminators on these? Seems to work well but the jobs examples (TransferJob, PolicyJob, etc.) don't seem to do this.

2021-06-08 17:18 UTC, avolinsky approved these changes

2021-06-09 13:46 UTC, merged