ACT-1178 | adding entity type validators resource
portalarchitects/skysync-cli pull request #185
Opened 2021-06-11 14:26 UTC by bentatum

2021-06-11 15:50 UTC, gotvino reviewed
Don’t you need a change to [client](src/sdk/client.ts) to expose the validators rest entry point?

2021-06-15 12:57 UTC, smbecker requested changes

2021-06-15 12:57 UTC, smbecker commented on src/sdk/models/validators.ts
> +export interface Validator extends IEntityIdentifier<string> {
For consistency, I would change this to `EntityTypeValidator`

2021-06-15 20:47 UTC, smbecker approved these changes

2021-06-16 10:17 UTC, merged