CL99-63 | List users not filtering by active
portalarchitects/skysync-cli pull request #187
Opened 2021-06-14 09:24 UTC by DinuAlin

- Changed active property to status

2021-06-14 19:53 UTC, MicheleBuselli requested changes

2021-06-14 19:53 UTC, MicheleBuselli commented on src/commands/users/list.ts
> +				desc: 'Retrieves users acording to the given status. Status can only be "active" or "disabled"',
FIx spelling 'according'

2021-06-16 09:35 UTC, DinuAlin commented on src/commands/users/list.ts
> +				desc: 'Retrieves users acording to the given status. Status can only be "active" or "disabled"',
Done

2021-06-16 13:07 UTC, MicheleBuselli approved these changes

2021-06-16 13:52 UTC, merged