SF-7795 | Added new CLI commands for managing parallel write configuration
portalarchitects/skysync-cli pull request #215
Opened 2021-08-30 19:12 UTC by Alex-Murtha

Back end changes in this [PR](https://github.com/portalarchitects/skysync-vnext/pull/3484)

2021-08-30 21:35 UTC, MicheleBuselli requested changes
Not sure how to see the options for the update command. When I type 'skysync.js performance parallel_writes update' it returns the table, but shouldn't I see what the options are (requested and  max)?

2021-08-30 21:35 UTC, MicheleBuselli commented on src/commands/performance/parallel_writes/update.ts
> +	description: 'Display current performance configuration',
'Update' instead of 'Display'?

2021-08-31 13:16 UTC, Alex-Murtha commented on src/commands/performance/parallel_writes/update.ts
> +	description: 'Display current performance configuration',
Done

2021-08-31 13:51 UTC, MicheleBuselli approved these changes

2021-08-31 13:53 UTC, merged